<a href="https://colab.research.google.com/github/Varshith022006/GENRATIVE-AI-ASSIGNMENTS/blob/main/G_VarshithReddy_2303A52287_Ass_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, accuracy_score, f1_score, confusion_matrix

# Data from Table 1
y_actual_regression = np.array([20, 30, 40, 50, 60])
y_pred_regression = np.array([20.5, 30.3, 40.2, 50.6, 60.7])

# Calculate error metrics for regression
mae = mean_absolute_error(y_actual_regression, y_pred_regression)
mse = mean_squared_error(y_actual_regression, y_pred_regression)
rmse = np.sqrt(mse)
r2 = r2_score(y_actual_regression, y_pred_regression)

print("Regression Metrics:")
print("Mean Absolute Error (MAE):", mae)
print("Mean Squared Error (MSE):", mse)
print("Root Mean Squared Error (RMSE):", rmse)
print("R-squared (R2):", r2)

Regression Metrics:
Mean Absolute Error (MAE): 0.4600000000000016
Mean Squared Error (MSE): 0.24600000000000147
Root Mean Squared Error (RMSE): 0.49598387070549127
R-squared (R2): 0.99877


In [ ]:
# Data from Table 2
y_actual_classification = np.array([0, 0, 1, 0, 2, 0,
                                     0, 0, 1, 0, 2, 0,
                                     0, 1, 1, 2, 2, 1,
                                     0, 2, 1, 0, 2, 2,
                                     0, 2, 1, 2, 2, 2])

y_pred_classification = np.array([0, 0, 1, 1, 2, 0,
                                   0, 0, 1, 0, 2, 0,
                                   0, 1, 1, 2, 2, 1,
                                   0, 2, 1, 0, 2, 2,
                                   0, 2, 1, 2, 2, 2])

# Calculate evaluation metrics for classification
accuracy = accuracy_score(y_actual_classification, y_pred_classification)
f1 = f1_score(y_actual_classification, y_pred_classification, average='weighted')
confusion = confusion_matrix(y_actual_classification, y_pred_classification)

print("\nClassification Metrics:")
print("Accuracy:", accuracy)
print("F1 Score:", f1)
print("Confusion Matrix:\n", confusion)


Classification Metrics:
Accuracy: 0.9666666666666667
F1 Score: 0.9670531400966184
Confusion Matrix:
 [[11  1  0]
 [ 0  7  0]
 [ 0  0 11]]
